<?php

namespace IlrProfilesDataFeed;

trait DataReplacementsTrait {

  /**
   * Return a replaced title for a given title.
   *
   * If no replacement is found, the original title is returned.
   */
  protected function replaceTitle(string $title): string {
    return match ($title) {
      'AAD Program Assistant II' => 'AAD Program Assistant II',
      'Academic Advising Associate II' => 'Academic Advising Associate II',
      'Accounts Rep C04' => 'Accounts Representative',
      'Accounts Rep III' => 'Accounts Representative III',
      'Accounts Rep IV' => 'Accounts Representative IV',
      'Accounts Rep V' => 'Accounts Representative V',
      'Administrative Assistant C03' => 'Administrative Assistant',
      'Administrative Assistant C04' => 'Administrative Assistant',
      'Administrative Asst IV' => 'Administrative Assistant IV',
      'Administrative Asst V' => 'Administrative Assistant V',
      'Administrator III' => 'Administrator III',
      'Administrator IV' => 'Administrator IV',
      'Administrator VI' => 'Administrator VI',
      'Administrator VII - ILR' => 'Administrator VII',
      'Admissions Associate I' => 'Admissions Associate I',
      'Admissions Associate II' => 'Admissions Associate II',
      'Annual Fund Officer III' => 'Annual Fund Officer III',
      'Applications Programmer II' => 'Applications Programmer II',
      'Applications Programmer III' => 'Applications Programmer III',
      'Applications Programmer IV' => 'Applications Programmer IV',
      'Applications Programmer IV-SP' => 'Applications Programmer IV-SP',
      'Bldg Coord III' => 'Building Coordinator III',
      'Building Coordinator C04' => 'Building Coordinator',
      'College Registrar' => 'College Registrar',
      'Communication Mgr I' => 'Communication Manager I',
      'Communication Mgr II' => 'Communication Manager II',
      'Communication Spec C06' => 'Communication Specialist',
      'Communication Spec II' => 'Communication Specialist II',
      'Communication Spec III' => 'Communication Specialist III',
      'Coord Program C06' => 'Program Coordinator',
      'Coord Program C07' => 'Program Coordinator',
      'Coord Program I' => 'Program Coordinator I',
      'Coord Program II' => 'Program Coordinator II',
      'Coord Program III' => 'Program Coordinator III',
      'Dean Assoc' => 'Associate Dean',
      'Dept Chairperson' => 'Chair',
      'Dir Acad' => 'Director',
      'Dir Assoc' => 'Associate Director',
      'Director Academic Advising' => 'Director of Academic Advising',
      'Director Admissions' => 'Director of Admissions',
      'Director Human Resources II - ILR' => 'Director Human Resources II',
      'Director Student Career Services' => 'Director of Student Career Services',
      'Director Student Services' => 'Director of Student Services',
      'Editor II' => 'Editor II',
      'Editor III' => 'Editor III',
      'Event/Conference Coord II' => 'Event/Conference Coordinator II',
      'Exec Staff Asst II' => 'Executive Staff Assistant II',
      'Extension Associate' => 'Extension Associate',
      'Extension Associate - SP' => 'Extension Associate',
      'Extension Associate Sr' => 'Extension Associate Sr',
      'Extension Associate Sr - SP' => 'Extension Associate Sr',
      'Extension Supp Spec C06' => 'Extension Support Specialist',
      'Extension Supp Spec I' => 'Extension Support Specialist I',
      'Extension Supp Spec II' => 'Extension Support Specialist II',
      'Extension Supp Spec II' => 'Extension Support Specialist III',
      'Extension Support Spec I - SP' => 'Extension Support Specialist I',
      'Fellow Visiting' => 'Visiting Fellow',
      'Finance Specialist II' => 'Finance Specialist II',
      'Finance Specialist III' => 'Finance Specialist III',
      'Finance Specialist IV' => 'Finance Specialist IV',
      'Food Service Worker S04' => 'Food Service Worker',
      'HR Generalist II' => 'HR Generalist II',
      'HR Generalist IV' => 'HR Generalist IV',
      'Human Resources Asst IV' => 'Human Resources Assistant IV',
      'Info Tech Area Mgr I' => 'Information Technology Area Manager I',
      'Info Tech Asst Dir I' => 'Information Technology Assistant Director I',
      'Info Tech Asst Dir II' => 'Information Technology Assistant Director II',
      'Informatics/Data Analyst III' => 'Informatics/Data Analyst III',
      'Instructional Tech Spec III' => 'Instructional Technology Specialist III',
      'Instructor' => 'Instructor',
      'Instructor Courtesy' => 'Instructor',
      'IT Support Assistant C05' => 'Information Technology Support Assistant',
      'IT Support Asst IV' => 'Information Technology Support Assistant IV',
      'Lecturer' => 'Lecturer',
      'Lecturer Sr' => 'Senior Lecturer',
      'Lecturer Visiting' => 'Visiting Lecturer',
      'Major Gifts Ofcr III' => 'Major Gifts Officer III',
      'Major GIfts Ofcr IV' => 'Major Gifts Officer IV',
      'Mgr Facilities I' => 'Facilities Manager I',
      'Mgr Finance I' => 'Manager of Finance I',
      'Mgr Finance III' => 'Mgr Finance III',
      'Multi Media Asst IV' => 'Multimedia Assistant IV',
      'Multimedia Producer' => 'Multimedia Producer',
      'Post Dr Assoc' => 'Postdoctoral Associate',
      'Prof Assoc' => 'Associate Professor',
      'Prof Asst' => 'Assistant Professor',
      'Prof Emeritus' => ' Emeritus Professor',
      'Professor' => 'Professor',
      'Prog Analyst III' => 'Programmer Analyst III',
      'Prog Analyst III' => 'Programmer Analyst Spec',
      'Prog Analyst Spec' => 'Programmer Analyst III',
      'Program Assistant I' => 'Program Assistant I',
      'Program Assistant II' => 'Program Assistant II',
      'Project Associate I' => 'Project Associate I',
      'Project Associate II' => 'Project Associate II',
      'Research Administration Assistant' => 'Research Administration Assistant',
      'Research Administration Manager' => 'Research Administration Manager',
      'Research Administration Specialist' => 'Research Administration Specialist',
      'Research Aide IV' => 'Research Aide IV',
      'Research Associate' => 'Research Associate',
      'Research Associate Sr' => 'Research Associate Sr',
      'Research Professor' => 'Research Professor',
      'Research Support Spec C06' => 'Research Support Specialist',
      'Research Support Spec C07' => 'Research Support Specialist',
      'Research Support Spec I' => 'Research Support Specialist I',
      'Research Support Spec II' => 'Research Support Specialist II',
      'RTE Director' => 'Director',
      'Scholar Visiting' => 'Visiting Scholar',
      'Staff Writer I' => 'Staff Writer I',
      'Student Career Services Associate II' => 'Student Career Services Associate II',
      'Student Services Asst IV' => 'Student Services Assistant IV',
      'Student Services Asst V' => 'Student Services Assistant V',
      'Student Svc Assoc II' => 'Student Services Associate II',
      'Student Svc Assoc IV' => 'Student Services Associate IV',
      'Systems Administrator III' => 'Systems Administrator III',
      'Teaching Supp Spec II' => 'Teaching Support Specialist II',
      'Temporary Administrative Assistant, Senior' => 'Temporary Administrative Assistant, Senior',
      'Temporary Editor/Writer' => 'Temporary Editor/Writer',
      'Temporary Extension Support' => 'Temporary Extension Support',
      'Temporary Programmer/Analyst - SP' => 'Temporary Programmer/Analyst - SP',
      'Temporary Research Aide' => 'Temporary Research Aide',
      'Temporary Research Support - SP' => 'Temporary Research Support - SP',
      'Temporary Teaching Professional' => 'Temporary Teaching Professional',
      'Temporary Teaching Support - SP' => 'Temporary Teaching Support - SP',
      'User Interface/Exp Spec IV' => 'User Interface/Experience Specialist IV',
      'Web Designer II' => 'Web Designer II',
      'Web Designer II - SP' => 'Web Designer II',
      default => $title,
    };
  }

  /**
   * Return a replaced department name for a given department from workday.
   *
   * Throws an error if no department match is found.
   *
   * @throws \UnhandledMatchError
   */
  protected function replaceDepartment(string $department): string {
    return match ($department) {
      'Admissions Office' => 'Admissions Office',
      'Alumni Affairs & Development' => 'Alumni Affairs & Development',
      'Career Services' => 'Career Services',
      'Center for Advanced Research on Work' => 'Center for Applied Research on Work',
      'Center for Applied Research on Work' => 'Center for Applied Research on Work',
      'Climate Jobs Institute' => 'Climate Jobs Institute',
      'Cornell Forensics Society' => 'Cornell Forensics Society',
      'Ctr for Advanced Human Resource Studies' => 'Center for Advanced Human Resource Studies',
      'Dean\'s Office' => 'Dean\'s Office',
      'Department of Global Labor and Work' => 'Global Labor and Work',
      'EMHRM' => 'EMHRM',
      'Extension Administration' => 'Extension Administration',
      'Facilities' => 'Facilities',
      'Field Studies / Study Abroad' => 'Field Studies / Study Abroad',
      'Financial Operations & Budget Planning' => 'Financial Operations & Budget Planning',
      'Global Labor Institute' => 'Global Labor Institute',
      'Graduate Office' => 'Graduate Office',
      'Human Capital Development' => 'Human Capital Development',
      'Human Resource Studies' => 'Human Resource Studies',
      'Human Resources Office' => 'Human Resources Office',
      'ILR Buffalos Co-Lab' => 'Buffalo Co-Lab',
      'ILR Review' => 'ILR Review',
      'Institute for Compensation Studies' => 'Institute for Compensation Studies',
      'International & Comparative Labor' => 'International & Comparative Labor',
      'International Programs' => 'International Programs',
      'Ithaca Conference Center' => 'Ithaca Conference Center',
      'Labor & Employment Law' => 'Labor & Employment Law',
      'Labor Dynamics Institute' => 'Labor Dynamics Institute',
      'Labor Economics' => 'Economics',
      'Economics' => 'Economics',
      'Marketing & Communications' => 'Marketing & Communications',
      'New York City Conference Center' => 'New York City Conference Center',
      'Office of Student Services' => 'Office of Student Services',
      'Organizational Behavior' => 'Organizational Behavior',
      'Resident Outreach Department' => 'Resident Outreach Department',
      'Scheinman Institute' => 'Scheinman Institute',
      'Smithers Institute' => 'Smithers Institute',
      'Social Statistics' => 'Social Statistics',
      'Technology Services' => 'Technology Services',
      'Worker Institute' => 'Worker Institute',
      'Yang Tan Institute' => 'Yang Tan Institute',
    };
  }

}
